# Generated by Django 6.0.3 on 2026-05-01 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='spacepost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_space_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spacepost',
            name='title',
            field=models.CharField(default='Untitled Post', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SpaceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sportApp.spacepost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
