# Generated by Django 6.0.3 on 2026-05-03 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportApp', '0003_scorecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=100, unique=True)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('home_score', models.IntegerField(default=0)),
                ('away_score', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=100)),
                ('game_date', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='scorecomment',
            name='game_id',
        ),
        migrations.AddField(
            model_name='scorecomment',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sportApp.gamescore'),
        ),
    ]
