# Generated by Django 6.0.3 on 2026-05-14 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportApp', '0005_directmessage'),
        ('sportApp', '0005_friendship'),
    ]

    operations = [
    ]
