# Generated by Django 6.0.3 on 2026-05-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportApp', '0006_merge_0005_directmessage_0005_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gamescore',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='game_date',
            field=models.DateField(),
        ),
    ]
